version: "2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "9000:9000"
      - "35729:35729"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
