FROM node:6

MAINTAINER Alexey Zakharov <zangular@yandex.ru>

RUN npm install -g bower grunt-cli

WORKDIR /usr/local/webstarter

COPY ./package.json /usr/local/webstarter/package.json
RUN npm install

COPY ./client /usr/local/webstarter/client
COPY ./server /usr/local/webstarter/server
COPY ./Gruntfile.js /usr/local/webstarter/Gruntfile.js

COPY ./.bowerrc /usr/local/webstarter/.bowerrc
COPY ./bower.json /usr/local/webstarter/bower.json
RUN bower install --allow-root

EXPOSE 9000
EXPOSE 35729

CMD ["grunt", "serve"]
