FROM node:6

MAINTAINER Alexey Zakharov <zangular@yandex.ru>

ENV NODE_ENV=production

WORKDIR /usr/local/webstarter
COPY ./dist/npm-shrinkwrap.json /usr/local/webstarter/npm-shrinkwrap.json
COPY ./dist/package.json /usr/local/webstarter/package.json
RUN npm install --production

COPY ./dist/public /usr/local/webstarter/public
COPY ./dist/server /usr/local/webstarter/server

EXPOSE 8088

CMD ["node", "server/app.js"]
