swagger: '2.0'
info:
  description: >-
    WebStarter is a boilerplate project. It's based on Angular Fullstack
    generator. It contains both: client and server.
  version: 1.0.0
  title: WebStarter
  contact:
    email: zangular@yandex.ru
host: '127.0.0.1:9000'
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /things:
    get:
      tags:
        - things
      summary: List all thing
      description: ''
      operationId: index
      responses:
        '200':
          description: All things stored
          schema:
            type: array
            items:
              $ref: '#/definitions/Thing'
    post:
      tags:
        - things
      summary: Add a new thing
      description: ''
      operationId: create
      parameters:
        - name: thing
          in: body
          description: Thing to be added
          required: true
          schema:
            $ref: '#/definitions/Thing'
      responses:
        '201':
          description: The thing has been added successfully
          schema:
            $ref: '#/definitions/Thing'
  '/things/{thingId}':
    parameters:
      - name: thingId
        in: path
        description: Thing ID
        required: true
        type: string
    get:
      tags:
        - things
      summary: Get thing by ID
      description: Returns a single thing
      operationId: show
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Thing'
        '404':
          description: Thing not found
    put:
      tags:
        - things
      summary: Update an existing thing
      description: ''
      operationId: update
      parameters:
        - name: thing
          in: body
          description: Thing to update the existing one
          required: true
          schema:
            $ref: '#/definitions/Thing'
      responses:
        '200':
          description: successful update
        '400':
          description: Invalid content supplied
        '404':
          description: Thing not found
    delete:
      tags:
        - things
      summary: Deletes a thing
      description: ''
      operationId: destroy
      responses:
        '200':
          description: The thing has been deleted successfully
        '404':
          description: Thing not found
definitions:
  Thing:
    type: object
    required:
      - name
    properties:
      _id:
        type: string
        readOnly: true
      name:
        type: string
        example: Greate feature of Angular Fullstack Generator
      info:
        type: string
      active:
        type: boolean
        default: true
